export const INIT_DATA = "INIT_DATA";
// export const GET_CATEGORIES = "GET_CATEGORIES";
export const UPDATE_TAB = "UPDATE_TAB";
export const UPDATE_FILTERS_NEW = "UPDATE_FILTERS_NEW";
export const UPDATE_SORTING = "UPDATE_SORTING";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const LOAD_MORE = "LOAD_MORE";
export const RESET_FILTERS = "RESET_FILTERS";
export const UPDATE_ALL_FROM_URL = "UPDATE_ALL_FROM_URL";